# Generated by Django 4.2.4 on 2023-09-14 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("employee_register", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Position1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title1", models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name="employee",
            name="emp_code",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name="Employee1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("employee_code", models.CharField(max_length=100, unique=True)),
                ("mobile", models.CharField(max_length=100)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employee_register.position1",
                    ),
                ),
            ],
        ),
    ]
